feat: routes created for each not-base-type params of every methods
DEIPworld/casimir-docs pull request #15
Opened 2022-04-18 17:34 UTC by ShmidtAlex

2022-04-18 18:38 UTC, euheny requested changes
- удалить все стили
- слассы в jsx написать статикой
- проверить нэйминг методов и переменных, чтобы они однозначно говорили о том, что делают/чему соответствуют

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +  name: 'CFuncPropsTable',
- откуда взялся префикс "С"?
- пропсы могут быть не только у метода
- в ишесах есть даже расписывание компонентов

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +    packageName: {
зачем сдесь передавать пакадж, если ты передаешь уже конкретный массив пропсов?

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +      const isType = getTypeDataByTypeName({ name: typeName, kind: 'typedef', package: props.packageName }).length > 0;
isType - название говорит о проверке тип это или нет. результатом же является поиск наличия типа в сторе. правильнее isTypeExist

> 0 - не имеет смысла. length уже означает что есть

props.packageName - использовать нельзя, так как тип может быть где угодно и проверка у тебя просто не сработает

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +      const isType = getTypeDataByTypeName({ name: typeName, kind: 'typedef', package: props.packageName }).length > 0;
название метода странное
getTypeDataByTypeName - ты в любом случае получаешь дата
getTypeByName - лучше, но в данном случае глупо. у нас геттер с возможностью выборки по фильтру. достаточно просто getType(...params)

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +          package: props.packageName
этот парам ты получаешь от доклета типа, а не забрасываешь снаружи. иначе ты перенаправишь пользователя к черту на рога

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +        ? <div class={'prop-content'}>{ typeName === '*' ? 'any' : typeName }</div>
зачем писать статические классы с объектном представлении?

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +      return (baseTypes.includes(typeName.toLowerCase()) || !isType
одна константа которая отвечает как ой будет нэйм any || typename
одна проверка на ретурн линка или дива

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +    const parseParams = (types) => types.map((type) => {
Плохое название. parseParams а работаешь только с типами
делать проверку на массив смысла нет. в тулбоксе есть хелпер wrapInArray который гарантировано вернет тебе массив. и дальше мапаешь

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +import { usePackagesData } from '@/stores/packages';
посмотри ишес #10

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.scss
> +.method-params {
я просил без стилизации. чисто на дефалтах так как я это все буду перписывать

2022-04-18 18:38 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +      { props.isTitle ? 'Params:' : null}
такой подход не позволит тебе переопределить заголовок. логичнее иметь в тайтле пустоту по дефалту или фалс и выводить по условию если тайтл присутствует

2022-04-18 18:53 UTC, euheny commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +          <th className={'th-params'}>name</th>
className - это реакт. версии TS тайпчек будет материться на ElementAttrs<HTMLAttributes>, так как там нет такого парама
во вьюхе просто class

2022-04-19 07:20 UTC, ShmidtAlex commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +          <th className={'th-params'}>name</th>
это гребаный линт все время переписывает class на className

2022-04-19 07:23 UTC, ShmidtAlex commented on src/components/CFuncPropsTable/CFuncPropsTable.jsx
> +  name: 'CFuncPropsTable',
стили удалить вообще все? Именование сделал по аналогии с другими компонентами (префикс C был твоим предложением ))

2022-04-21 08:18 UTC, euheny requested changes

2022-04-21 08:18 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +              getClassesByPackage(moduleName).map((el) => (
```
const list = getClassesByPackage(moduleName).map...

return (
  <div class="pack-list__entities">
    {list}
  <div>
)
```
старайся не использовать сложные конструкции внутри jsx/tsx - сильно осложняет чтение кода

2022-04-21 08:18 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +              getClassesByPackage(moduleName).map((el) => (
относится и к другим местам тоже

2022-04-21 08:18 UTC, euheny commented on src/components/DisplayExamples/index.js
> +import { DisplayExamples } from './DisplayExamples';
попрошу везде заменить на единый именованный реэкспорт. у нас нет причин поддерживать универсальность и при этом будем двигаться к единообразной структуре именованного использования

`export { DisplayExamples } from './DisplayExamples';`

2022-04-21 08:18 UTC, euheny commented on src/components/DisplayMethod/DisplayMethod.jsx
> +          { props.method.params?.length
как говорил ранее - лучше выносить. думается мне разве что инлайновые проверки каких-то примитивов можно в jsx и то (для сохранения единообразия) стоит выносить, чтобы код был максимально легкочитаемым

2022-04-21 08:18 UTC, euheny commented on src/components/DisplayParams/DisplayParams.jsx
> +      const warning = type.length > 1 ? <span style='color: red'>✘</span> : '';
все что возвращает jsx делать методами, чтобы отработало наверняка

2022-04-21 08:18 UTC, euheny commented on src/views/ClassDetails/ClassDetails.jsx
>  import { useRoute } from 'vue-router';
related to #14
для класса отдельный компонент. на вьюхе вызываем компонент и кормим ему данные

2022-04-21 08:18 UTC, euheny commented on src/views/ComponentDetails/ComponentDetails.jsx
>          { displayName: route.params.component, package: route.params.package }
мне кажется лучше использовать name, а не displayName для выборки и роутинга. displayName может быть "литературным" и содержать в себе что угодно

2022-04-21 08:18 UTC, euheny commented on src/views/ComponentDetails/ComponentDetails.jsx
> +    const renderProps = (props) => {
у нас уже есть компонент для пропсов. логичнее его и использовать. учитывая, что модель данных может отличаться - можно по месту подель компонента привести к виду, который будет перевариваем копонентом парамсов. или же в компоненте парамсов задать "удобную" модель и приводить к ней и компоненты и другие доклеты (рассмотри варианты)

2022-04-21 08:28 UTC, ShmidtAlex commented on src/views/ComponentDetails/ComponentDetails.jsx
>          { displayName: route.params.component, package: route.params.package }
дело в том, что у компонентов нет поля name, у них это называется displayName

2022-04-21 09:21 UTC, ShmidtAlex commented on src/components/CNavigationTree/CNavigationTree.jsx
> +              getClassesByPackage(moduleName).map((el) => (
избавился

2022-04-21 12:02 UTC, ShmidtAlex commented on src/views/ComponentDetails/ComponentDetails.jsx
> +    const renderProps = (props) => {
это обертка для компонента DisplayProps, она нужна исключительно для проверки - есть ли данные для компонента DisplayProps

2022-05-17 07:57 UTC, euheny approved these changes

2022-05-17 07:57 UTC, merged