feat: component NotFound and FeatureView created, dynamics routes added
DEIPworld/casimir-docs pull request #4
Opened 2022-03-25 20:53 UTC by ShmidtAlex

feat: New view for features created

2022-03-30 06:24 UTC, euheny requested changes

2022-03-30 06:24 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +          path: `/package/${filterParentName(el.package)}/${el.kind}/${el.name}`,
в роутинге настоятельно не рекомендую использовать path. если у нас пачка мест где это есть и нам понадобилось изменить роутинг - придется в куче мест редактировать. намного оптималььнее использовать именные ссылки на роут

2022-03-30 06:24 UTC, euheny commented on src/router/index.js
> +  },
не стоит такое делать (допустимо, но не стоит)
- контекст роута лучше делать через чайлды
- именуем в латинице через точку в зависимости от парента
- желательно на каждом уровне иметь маркер типа (в данном случае у тебя выпало все кроме компонентов
- для проходных страниц можно использовать компонент-хэлпер из @deip/platform-util `routerView` он рендерит только роутер вью. ну или по месту пилить `component: { template: '<router-view />' }`

итого мы получим что-то типа:

```
{
  path: '/packages/:package',
  name: 'package',
  component: routerView,
  children: [
    {
      path: 'components/:component,
      name: 'package.component',
      component: ComponentDetails,
    },
    // как более детализированная альтернатива, если мы хотим сделать листовые страницы
    {
      path: 'components,
      name: 'package.components',
      component: routerView,
      children: [
        {
          path: '',
          name: 'package.components',
          component: ComponentsList,
        },
        {
          path: ':component',
          name: 'package.component.details',
          component: ComponentDetails,
        }
      ]
    },
    // конец альтернативы
    {
      path: 'classes/:class,
      name: 'package.class',
      component: ClassDetails,
    },
    {
      path: 'functions,
      name: 'package.functions',
      component: FunctionsDetails,
    },
    ...
  ]
```

2022-04-04 11:06 UTC, euheny requested changes

2022-04-04 11:06 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +      packages, getClasses, getMethods, getComponents, getTypes, getConstants
не обязательно префексировать

2022-04-04 11:06 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +      return list.filter((el) => el.moduleName === moduleName).map(
не понимаю смысла этого фильтра если его можно делать на уровне геттера

2022-04-04 11:06 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +        <div class="pack-list__name">{pack.name}</div>
такие конструкции в верстке не используются ul > li

2022-04-04 11:06 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +          <div>{showVerboseFeature(pack.name, getClasses).length ? 'CLASSES' : ''}</div>
конструкция с условием вообще не понятна так как ниже нет объективной проверки на сам блок

2022-04-04 11:06 UTC, euheny commented on src/stores/packages.js
> +    getClasses(state) {
подразумевалось, что геттер возвращает лист на основе запрошенного пакаджа, чтобы не фильтровать это дело в самом компоненте. можно фильтровать руками, можно установить @deip/toolbox и использовать оттуда готовые методы выборки

2022-04-04 11:06 UTC, euheny commented on src/utils/NavElemCreator.js
> +export const createNavElement = (state, id) => {
назначение данного хелпера мне принципиально непонятно

2022-04-05 10:04 UTC, closed without merging

2022-04-05 10:04 UTC, ShmidtAlex commented
all changes are on another branch

2022-04-05 10:06 UTC, ShmidtAlex commented on src/components/CNavigationTree/CNavigationTree.jsx
> +      packages, getClasses, getMethods, getComponents, getTypes, getConstants
ты имеешь ввиду  префикс get?