fix: refactoring finished
DEIPworld/casimir-docs pull request #5
Opened 2022-04-05 09:30 UTC by ShmidtAlex

2022-04-05 10:46 UTC, euheny requested changes

2022-04-05 10:46 UTC, euheny commented on package.json
> +    "save-dev": "0.0.1-security",
лувый инстал, скорее всего опечатка в консоли была

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +      const clearedName = typeof el === 'string' ? el.slice(6) : '';
в тулбоксе есть метод isString, при этом сама структура роута не совсем понятна

```
/packages/:package/components/:component
/packages/:package/classes/:class
/packages/:package/methods
...
```
не понятно для чего нужен какой-то clearedName

type - обязателен. без него не взлетит построение роутинга, а вот verbose уже может иметь дефалт

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const getMethods = (moduleName) => {
именование методов

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const isClasses = (type, moduleName) => (getClassesByPackage(moduleName).length ? type : '');
именование
is, has в имени метода подразумевает ретурн булевого значения

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +        <ul class="pack-list__entities">
значительно логичнее весь блок секции держать в генераторе, так как именно в нем можно произвести проверку, что есть данные и просто вернуть null если данных нет. в твоем случае ты делаешь проверку на заголовок, вызываешь генератор и если данных нет у тебя зарендерит пустые блоки

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +         <ul className="pack-list__entities">
Структура верски: `ul > li > div` если уж пилить навигацию на списке, то по правилам и семантике

2022-04-05 10:46 UTC, euheny commented on src/router/index.js
> +        path: '/package/:package',
ошибка пути. это потомок и должен быть просто `constants`

2022-04-05 10:46 UTC, euheny commented on src/router/index.js
> +        path: '/package/:package',
ошибка пути. это потомок и должен быть просто `functions` или `methods`

2022-04-05 10:46 UTC, euheny commented on src/router/index.js
> +        path: '/package/:package',
ошибка пути. это потомок и должен быть просто `typedefs` или `types`

2022-04-05 10:46 UTC, euheny commented on src/stores/packages.js
> +    getClassesByPackage: () => (pack) => collectionList(jsdocs, { package: pack, kind: 'class' }),
рекомендую для пропсов в таких ситуациях применять именование в соответствии с ключем
```
(package) => collectionList(jsdocs, { package, kind: 'class' })
```
позволяет в объектах не прописывать отдельно ключ/значение

2022-04-05 10:46 UTC, euheny commented on src/views/TypeDefsDetails.vue
> +<style scoped>
не оставляем артефакты

2022-04-05 10:46 UTC, euheny commented on src/views/FunctionDetails.vue
> +<style scoped>
не оставляем артефакты

2022-04-05 10:46 UTC, euheny commented on src/views/ConstantDetails.vue
> +<style scoped>
не оставляем артефакты

2022-04-05 10:46 UTC, euheny commented on src/views/ComponentDetails.vue
> +<style scoped>
не оставляем артефакты

2022-04-05 10:46 UTC, euheny commented on src/views/ClassDetails.vue
> +<style scoped>
не оставляем артефакты

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const isComponents = (type, moduleName) => (getComponentsByPackage(moduleName).length ? type : '');
само наличие этих проверок не имеет смысла. за их рендер должен отвечать соответсвующий генератор

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const getConstants = (moduleName) => {
именование методов

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const getTypes = (moduleName) => {
именование методов

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const getComponents = (moduleName) => getComponentsByPackage(moduleName).map((el) => (
именование методов

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const getClasses = (moduleName) => getClassesByPackage(moduleName).map((el) => (
именование методов
get - получить данные
в данном случае более корректно использовать что-то типа render, generate, gen. чтобы префикс явно указывал на функциональность метода

2022-04-05 10:46 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const createRoute = (el, verbose, type = '') => {
я бы упростил метод примерно до:

```
createRoute(package, section = '', childProps = {}) {
  return {
    name: section ? `package.${section}` : 'package',
    params: {
      package: `${clearedName}-${type}`,
      ...childProps
    }
  };
}
```

2022-04-05 11:23 UTC, ShmidtAlex commented on src/stores/packages.js
> +    getClassesByPackage: () => (pack) => collectionList(jsdocs, { package: pack, kind: 'class' }),
дело в том, что линт ругается, говорит что package зарезервированное слово

2022-04-05 11:49 UTC, ShmidtAlex commented on src/router/index.js
> +        path: '/package/:package',
тогда предупреждение выскакивает Absolute path "/typedefs" should have the exact same param named "package" as its parent "/packages/:package".

2022-04-06 09:46 UTC, ShmidtAlex commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const createRoute = (el, verbose, type = '') => {
здесь нужна именно проверка на тип данных, потому что может быть строка, а может быть объект

2022-04-06 09:49 UTC, ShmidtAlex commented on src/components/CNavigationTree/CNavigationTree.jsx
> +    const createRoute = (el, verbose, type = '') => {
помимо этого, у компонентов отсутствует kind, поэтому сильно не упрощается

2022-04-07 11:45 UTC, euheny approved these changes

2022-04-07 11:45 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +               <li class="pack-list__entities-item">{el.name}</li>
li > router-link, а не наоборот

2022-04-07 11:45 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +        <div>{getClassesByPackage(moduleName).length ? 'CLASSES' : ''}</div>
ul > li

2022-04-07 11:45 UTC, merged