feat: draft for Clasdetails
DEIPworld/casimir-docs pull request #6
Opened 2022-04-07 21:53 UTC by ShmidtAlex

2022-04-08 09:31 UTC, euheny approved these changes, later dismissed

2022-04-08 09:31 UTC, euheny commented on src/stores/packages.js
> +    getClassData: () => (...params) => collectionOne(jsdocs, ...params),
в данном случае спред-оператор не нужен так как там объект. если подходить таким макаром то резонеее` getClassData: () => (query)` но я бы рекомендовал свести это к 
```
getClassData: (state) => (package, name) => collectionOne(state.jsdocs, { package, name })
```
так как более четко ограничивает область получения данных. тот же класс или компонент или что угодно может оказаться одноименным в разных пакаджах

2022-04-08 09:31 UTC, euheny commented on src/stores/packages.js
> +    getComponentsByPackage: () => (pack) => collectionList(components, { package: pack }),
поправь геттеры чтоб они работали со стейтом а не с импортированными данными
someGetter: (state) => (params) => state.components

2022-04-08 09:31 UTC, euheny commented on src/views/ClassDetails.vue
> +    <h3 class="feature-type">
попробуй переделать на jsx

2022-04-08 09:31 UTC, euheny commented on src/views/ComponentDetails.vue
>  <template>
попробуй переделать на jsx

2022-04-08 09:55 UTC, ShmidtAlex commented on src/views/ClassDetails.vue
> +    <h3 class="feature-type">
а это же vue файл - это не будет противоречием? Или создать компонент что-то вроде ClassDetailsContent.jsx?

2022-04-08 09:57 UTC, euheny commented on src/views/ClassDetails.vue
> +    <h3 class="feature-type">
ну так и сам файл переименовать )))))

2022-04-11 22:18 UTC, euheny requested changes
С большего вроде норм. Если что - скореектируем по ходу.
Пройдись линтером - страдает форматирование.
В прошлом ПР упустил

```
const generateClasses = (moduleName) => (
      <div class="pack-list__entities">
        <div>{getClassesByPackage(moduleName).length ? 'CLASSES' : ''}</div>
          {getClassesByPackage(moduleName).map((el) => (
          <div className="pack-list__entities-item">
            <router-link to={
              createRoute(
                moduleName,
                'class',
                { [el.kind]: el.name || el.displayName, package: el.package }
              ) }>
               {el.name}
            </router-link>
          </div>
          ))
        }
      </div>
    );
```
такие блоки надо целиком заворачивать в условие
```
const generateClasses = (moduleName) => getClassesByPackage(moduleName).length ? (
<div class="pack-list__entities">...</div>
) : null
```
иначе будут пустые блоки при отсутсвии данных

2022-04-11 22:18 UTC, euheny commented on src/components/CNavigationTree/CNavigationTree.jsx
> +                { [el.kind]: el.name || el.displayName, package: el.package }
`[el.kind]` не имеет смысла, мы и так знает какой там парам для роута
`el.name || el.displayName` что-то мне подсказывает, что нэйм там будет полюбому

2022-04-12 09:31 UTC, ShmidtAlex commented on src/components/CNavigationTree/CNavigationTree.jsx
> +                { [el.kind]: el.name || el.displayName, package: el.package }
да, точно - рудимент от более универсального кода остался

2022-04-12 09:47 UTC, euheny approved these changes

2022-04-12 09:47 UTC, merged